<a href="https://colab.research.google.com/github/Akanksha-Ceris/NumPy-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is NumPY
: Numpy is the fundamental package for scientific computing  in Pyhton . It is a Python library that provides a multidimensional array object,various derived objects(such as masked arrays and matrices)

Creating Numpy Arrays

In [ ]:
#np.array
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


# 3D numpy array


In [ ]:
c = np.array([[[1,2,3],[4,5,6],[7,1,2]]])#Tensor
print(c)

[[[1 2 3]
  [4 5 6]
  [7 1 2]]]


In [ ]:
# datatype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
np.array([3,4,5],dtype=bool)

array([ True,  True,  True])

In [ ]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#ap.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshpae
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.3464382 , 0.05571864, 0.22865066, 0.59158401],
       [0.82339972, 0.36768507, 0.81978299, 0.9635211 ],
       [0.24480142, 0.70044866, 0.09518248, 0.85068578]])

In [ ]:
# np.linspace
# full name is linear space
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.random.random((2,4))

array([[0.07612283, 0.22926227, 0.49937224, 0.45546854],
       [0.007139  , 0.13574449, 0.72495819, 0.01523502]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
#np.Identity
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# with reshape\
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

Array Attributes


In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4,)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
print(a1.ndim)

1


In [ ]:
print(a2.ndim)

2


In [ ]:
print(a3.ndim)

3


In [ ]:
#Shape
a2.shape


(3, 4)

In [ ]:
print(a3.shape)


(2, 2, 2)


In [ ]:
#size : it provide how many number of element in any numpyarray
a3.size

8

In [ ]:
print(a2.size)
print(a2)

12
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
print(a1.size)
a1

10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2.itemsize

8

In [ ]:
#itemsize
a3.itemsize

8

In [ ]:
a1.itemsize

8

In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing Datatype

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation


In [ ]:
a1 =np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#scalar operations
# arith
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a1 +3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [ ]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
#relational
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#relational
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2>25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a1 +a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])