<a href="https://colab.research.google.com/github/Akanksha-Ceris/NumPy-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is NumPY
: Numpy is the fundamental package for scientific computing  in Pyhton . It is a Python library that provides a multidimensional array object,various derived objects(such as masked arrays and matrices)

Creating Numpy Arrays

In [ ]:
#np.array
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


# 3D numpy array


In [ ]:
c = np.array([[[1,2,3],[4,5,6],[7,1,2]]])#Tensor
print(c)

[[[1 2 3]
  [4 5 6]
  [7 1 2]]]


In [ ]:
# datatype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
np.array([3,4,5],dtype=bool)

array([ True,  True,  True])

In [ ]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#ap.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshpae
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.18012037, 0.6252578 , 0.87653347, 0.83031768],
       [0.61141287, 0.30582737, 0.38179185, 0.05927892],
       [0.92812106, 0.78825012, 0.10618298, 0.41877151]])

In [ ]:
# np.linspace
# full name is linear space
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.random.random((2,4))

array([[0.53362136, 0.84250011, 0.49438404, 0.11208029],
       [0.88172658, 0.3366735 , 0.77164939, 0.44549983]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
#np.Identity
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# with reshape\
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

Array Attributes


In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4,)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
print(a1.ndim)

1


In [ ]:
print(a2.ndim)

2


In [ ]:
print(a3.ndim)

3


In [ ]:
#Shape
a2.shape


(3, 4)

In [ ]:
print(a3.shape)


(2, 2, 2)


In [ ]:
#size : it provide how many number of element in any numpyarray
a3.size

8

In [ ]:
print(a2.size)
print(a2)

12
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
print(a1.size)
a1

10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2.itemsize

8

In [ ]:
#itemsize
a3.itemsize

8

In [ ]:
a1.itemsize

8

In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing Datatype

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation


In [ ]:
a1 =np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#scalar operations
# arith
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a1 +3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [ ]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
#relational
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#relational
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2>25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a1 +a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
#scalar operation
# arithmetic



In [ ]:
# max/min/sum/prod


Array Function
numpy provides so many functions.

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[70., 29., 21.],
       [31., 69., 25.],
       [34.,  2., 13.]])

In [ ]:
#max/min/sum/prod
np.max(a1)

np.float64(70.0)

In [ ]:
#min
np.min(a1)

np.float64(2.0)

In [ ]:
#sum
np.sum(a1)

np.float64(294.0)

In [ ]:
#prod
np.prod(a1)

np.float64(2015201097000.0)

In [ ]:
np.max(a1,axis= 0)
#0 - >col and 1 - >row

array([70., 69., 25.])

In [ ]:
print(a1)

[[70. 29. 21.]
 [31. 69. 25.]
 [34.  2. 13.]]


In [ ]:
np.max(a1,axis = 0)

array([70., 69., 25.])

In [ ]:
np.max(a1,axis = 1)

array([70., 69., 34.])

In [ ]:
np.min(a1,axis=0)

array([31.,  2., 13.])

In [ ]:
np.min(a1,axis = 1)

array([21., 25.,  2.])

In [ ]:
np.prod(a1,axis = 0)

array([73780.,  4002.,  6825.])

In [ ]:
# mean / median/std/var
np.median(a1,axis = 1)

array([29., 31., 13.])

In [ ]:
np.std(a1,axis=1)

array([21.46314671, 19.48218559, 13.27487183])

In [ ]:
np.var(a1,axis=1)

array([460.66666667, 379.55555556, 176.22222222])

In [ ]:
#rignometric functions
np.sin(a1)

array([[ 0.77389068, -0.66363388,  0.83665564],
       [-0.40403765, -0.11478481, -0.13235175],
       [ 0.52908269,  0.90929743,  0.42016704]])

In [ ]:
#dot product
a2= np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponeets
np.log(a1)

array([[4.24849524, 3.36729583, 3.04452244],
       [3.4339872 , 4.2341065 , 3.21887582],
       [3.52636052, 0.69314718, 2.56494936]])

In [ ]:
# round /floor/cell
np.random.random((2,3))*100

array([[71.77975875, 72.34138558, 92.51094311],
       [65.30417819, 21.98716623,  7.44592692]])

In [ ]:
# if i want integer number then i have to round the number
np.round(np.random.random((2,3))*100)

array([[85., 28., 32.],
       [57., 30.,  6.]])

In [ ]:
#ceil
np.ceil(np.random.random((2,3))*100)

array([[99., 90., 64.],
       [21.,  1., 99.]])

Indexing and slicing


In [ ]:
a1 = np.arange(10)
a2=np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[-1]

np.int64(9)

In [ ]:
a1[0]

np.int64(0)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
a2[2,3]

np.int64(11)

In [ ]:
a2[1,0]

np.int64(4)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# how i can find 5


In [ ]:

#Once numpy is installed , import it in  your applications by adding  the import keyword.
import numpy

In [ ]:
import numpy
arr= numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Checking numpy version
the version string is stored  under -version- attribute


In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Numpy creating array

create a numpy ndarray object
numpy is used to work with arrays. The array object in Numpy is called  ndarray. we can create a numpy ndarray object by using the array() function.


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type (arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# use a tuple to create a NUmpy array:
import numpy as np
arr= np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

0D - Arrays
o -D arrays , or scalars are the elements in an array. each value in an array is 0 d array.

In [ ]:
# create a 0 d array with value 42
import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
# create a 1_d array containing the values 1,2,3,4,5:
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
# create a 2 -D array containg two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


3 _D arrays
an array that has 2 d arrays (matrices ) as its elements is called 3 - d array.
 These are often used to represent a 3 rd order tensor


In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions?


In [ ]:
# numpy arrays provides the ndim attributes that returns an integer that tells us how many dimesnions the array have.
# check  how many dimesions the arrays have:
a = np.array(42)
b = np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Iterrating

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for i  in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


In [ ]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


Reshaping

In [ ]:
# reshape


In [ ]:
#Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#ravel
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

Stacking


In [ ]:
# horizontal stacking
#  [2 * 2] [ 2 * 2]- stack
# [2 * 4] or [ 4 *2]
a4 = np.arange(12).reshape(3,4)

a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# vertical staking
np.hstack ((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Spliting


In [ ]:
#  hsplit
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical split
np.hsplit(a4)

TypeError: hsplit() missing 1 required positional argument: 'indices_or_sections'

In [ ]:
# vsplit
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [ ]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division

Numpy array vs Python lists

In [ ]:
# speed
#list
# numpy
# memory


In [ ]:
 # speed
 # list
a = [i for i in range(10000000)]
b =[i for i in range(10000000,20000000)]
c = []
import time
start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)



2.2126994132995605


In [ ]:
# numpy
import numpy as np
a = np.arange(10000000)
b =np.arange(10000000,20000000)
start = time.time()

c= a +b
print(time.time()-start)



0.19313311576843262


In [ ]:
2.21/0.19

11.631578947368421

In [ ]:
# memory
#  advantage in term of memory
a = [ i for i in range(1000000)]
import sys
sys.getsizeof(a)



8448728

In [ ]:
# I will crate one numpy array
a = np.arange(10000000,dtype = np.int16)
sys.getsizeof(a)

20000112

In [ ]:
a = np.arange(10000000,dtype = np.int8)
sys.getsizeof(a)

10000112

In [ ]:
# list can store non homogeneous element b ut numpy can  not
# Normal indexxing and slicing
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a[1,2]

np.int64(5)

In [ ]:
# slicing
a[1:3,1 :3]

array([[26, 15],
       [50, 56]])

In [ ]:
# # fancy indexing
# # Boolean indexing
# import  numpy  as np
# a = np.random.randint(1,100,24).reshape(6,4)
# a


array([[59, 11, 31, 43],
       [60, 26, 15, 24],
       [ 3, 50, 56, 42],
       [61, 42, 87,  4],
       [27, 53, 83,  4],
       [ 4, 33, 63, 62]])

In [ ]:
# fancy indexing
a[[0,2,3]]

array([[59, 11, 31, 43],
       [ 3, 50, 56, 42],
       [61, 42, 87,  4]])

In [ ]:
a[[0,2,3,5]]

array([[59, 11, 31, 43],
       [ 3, 50, 56, 42],
       [61, 42, 87,  4],
       [ 4, 33, 63, 62]])

In [ ]:
#Fancy Indexing
a[:,[0,2,3]]

array([[59, 31, 43],
       [60, 15, 24],
       [ 3, 56, 42],
       [61, 87,  4],
       [27, 83,  4],
       [ 4, 63, 62]])

In [ ]:
# Boolean Indexing
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[79, 80, 82, 33],
       [41, 81, 56, 24],
       [71, 65, 48, 23],
       [ 8, 55, 63, 44],
       [70, 95,  2, 83],
       [26, 95, 98, 78]])

In [ ]:
# find all number greater than  50
a[a>50]

array([79, 80, 82, 81, 56, 71, 65, 55, 63, 70, 95, 83, 95, 98, 78])

In [ ]:
# find out even numbers
a % 2 == 0

array([[False,  True,  True, False],
       [False, False,  True,  True],
       [False, False,  True, False],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True]])

In [ ]:
# find all number greater than  50 and aree even
(a >50) & (a % 2 == 0)

array([[False,  True,  True, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False,  True,  True]])

# find all number greater than 50 and are even


In [ ]:
a[(a >50) & (a % 2==0)]


array([80, 82, 56, 70, 98, 78])

In [ ]:
# find all number  not divisible by 7
a[a % 7 != 0]

array([79, 80, 82, 33, 41, 81, 24, 71, 65, 48, 23,  8, 55, 44, 95,  2, 83,
       26, 95, 78])

In [ ]:
a[~(a  %  7 == 0)]

array([79, 80, 82, 33, 41, 81, 24, 71, 65, 48, 23,  8, 55, 44, 95,  2, 83,
       26, 95, 78])

In [ ]:
# and is called logical operator
# & is called bitwise operator


# **Brodcasting**

The term broadcasting describe  how numpy treats arrays with different shapes during arithmetic operations.
The smaller arraay is "broadcast" across the larger so that they have compatible  shape


In [ ]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(a +b)

[[ 6  8 10]
 [12 14 16]]


In [ ]:
# diff shpae
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print(a +b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [ ]:
# get the first element from the following array:
import numpy as np
arr  = np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr = np.array(["akanksha","Abhi"])
print(arr[0])

akanksha


In [ ]:
# get the second element from an array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1])

2


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row', arr[0 ,1])

2nd element on 1st row 2


In [ ]:
print(' 5 th element on 2nd row',arr[1,4])

 5 th element on 2nd row 10


In [ ]:
# Access the third element of the second array of the first array:
arr = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])


6


In [ ]:
# print the last element from the 2nd dim:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim:',arr[1,-1])

Last element from 2nd dim: 10


#

In [1]:
# convert the array into a 1 D array;
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
newarr= arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


Numpy Array Iterationg
iterating means going through elements one by one
As we deal with multi-dimensional arrays in numpy , we can do this using basic for loop of python
if we  iterate on a 1 d array it will go through  each element one by one


In [3]:
# Iterate on the elements  of the following 1 - D array:
import numpy as np
arr= np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [4]:
# Iterating a 2 D array;
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [5]:
# Iterate  on each scalar element of the  2 D array:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


In [9]:
# Iterating   3_ D arrays
# in  3 d array it will go through all the 2 d  arrays
# Iterate on the elements of the following 3 -D array:
import numpy as np
arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  for y in x:
    for i in y:
      print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [11]:
# Iterate through the array as a string
import numpy as np
arr= np.array([1,2,3])
for x in np.nditer(arr, flags=['buffered'],op_dtypes=['S']):
   print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


Iteration with Different step size
we can use filtering and followed by iteration
iterate through every scalar element of the   2D array skipping 1 element


In [12]:
import numpy as np
arr= np.array([[1,2,3,4],[5,6,7,8]])
for x in  np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


In [13]:
# Enumerated Iteration using ndenumerate()
# enumerated means mentioning sequence number of somethings one by one,
# sometimes we require corresponding index of the element while iteraitong, the ndenumerate() method can be used for those usecases.
# Enumerated on follwoing  1 D arrays elements:

In [14]:
# Enumerate on following 1 D arrays elements:
import numpy as np
arr= np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3


Numpy Joining Array
JOining NUmpy Arrays
joining means putting contests of two or more arrays in a single array.
In sql we join table based  on a key, whreas in Numpy we join arrays by axes
we pass  a sequnce of arrays  that we want to join to the concatenate() function , along with  the axis . If axis is not explicitly passed. it is taken  as o

In [16]:
# Join numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr= np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [19]:
arr1 = np.array(["apple","mango"])
arr2 = np.array(["banana","orange"])
arr = np.concatenate((arr1,arr2))
print(arr)

['apple' 'mango' 'banana' 'orange']


In [20]:
#join two 2 D arrays along rows (axis = 1):
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [21]:
# Joining Arrays Using stack functions
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr =np.stack((arr1,arr2),axis = 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [22]:
arr= np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [23]:
arr= np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


Splitting Numpy arrays
splitting is reverse operation of joining
joining merges multiple arrays  into one and splitting breaks one array into multiple
We use array_split() for splitting arrays, we pass it the array want to split and the number of splits


In [25]:
# split the array in 3 parts:
import numpy as np
arr= np.array([1,2,3,4,5,6])
newarr= np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [27]:
newarr = np.array_split(arr,8)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64)]


In [28]:
# access the splitted arrays:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr= np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [29]:
# spliting  2 d arrays
# use the same syntax when splitting 2 -D arrays.
# use the array_split() method pass in the array  u want to split and the number of split you want to do,
# split the 2 D array into three 2 - D array
import numpy as np
arr= np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [31]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
newarr= np.array_split(arr,3,axis =1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15]])]


In [32]:
newarr= np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15]])]
